### ISSUE TITLE
Error: Maximum length of the field is 4096. Field: apps.dynamite.CreateMessageInfo.text_body

### ISSUE THREAD

**Issue by jonathan-w-smith** [googleworkspace/hubot-google-hangouts-chat#12]
When users request help from the chatbot the Hangouts Chat API is erroring due to the length of the message being sent.

```
(node:74910) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:74910) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:74910) UnhandledPromiseRejectionWarning: Error: Maximum length of the field is 4096. Field: apps.dynamite.CreateMessageInfo.text_body
  at createError (/hubot/node_modules/axios/lib/core/createError.js:16:15)
  at settle (/hubot/node_modules/axios/lib/core/settle.js:18:12)
  at Unzip.handleStreamEnd (/hubot/node_modules/axios/lib/adapters/http.js:202:11)
  at Unzip.emit (events.js:208:15)
  at Unzip.EventEmitter.emit (domain.js:476:20)
  at endReadableNT (_stream_readable.js:1168:12)
  at processTicksAndRejections (internal/process/task_queues.js:77:11)
```
Depending on the content that may need to be sent the limitation of the Hangouts Chat API and how the adapter interacts with it could present a problem with sending appropriate responses.

**Comment by rtilikay** [comment]
Hi Jonathan, 

Unfortunately, the maximum length is set by Hangouts Chat and cannot be changed. Is it possible for you to shorten your documentation to fit under 4KB?

Alternatively, we could add an option to use paging for long messages, i.e. break text messages longer than 4KB into 4KB chunks and send them as multiple messages. Hangouts Chat already groups messages sent closer together, so the experience should be near-equivalent to sending a single, long message. Would that idea fit your use case?

**Comment by jonathan-w-smith** [comment]
I think implementing a paging system is the best solution.  I used help content as an example, but I can see many cases where it would be possible to end up with more content than the 4KB.   My team runs into this limit on an almost daily basis just using Hangouts Chat in everyday use.

**Comment by rtilikay** [comment]
Sounds good, I'll look into introducing this functionality.

**Comment by jpoehnelt** [comment]
Closing this issue as the repository is archived.
